### ISSUE TITLE
Cannot be normalizing  in parallel 

### ISSUE THREAD

**Issue by lovemefan** [v-nhandt21/Vinorm#6]
When using multithread to speed up processing data ，i found deranged data.  because the normalized text write in `output.txt` when another thread read it.
Looking forward to hearing from you soon.
Thanks.

**Comment by v-nhandt21** [comment]
This repo is python version which wrapper for C++ source. 

The python ver is used for preprocessing in Vietnamese TTS research only.

I can not share c++ because of some policy from my lab, but I have some tricks you can try for multithread.

Check out this script: https://github.com/v-nhandt21/Vinorm/blob/master/vinorm/__init__.py

You can create multiple input.txt files and call the process a the same time, 

[    I=A+"/input.txt"](https://github.com/v-nhandt21/Vinorm/blob/cf32b603a2dcab12c6d6218e92beebcd20facc6e/vinorm/__init__.py#L8)

In the future, I would review to refact this source code for easy-use.

**Comment by lovemefan** [comment]
Thank you for your suggestion 🙂

**Comment by Crazylov3** [comment]
Still not solved, right? We can create multiple input files; however, your binary main script is fixed to return output as "output.txt," leading to a race condition. How can I fix this
